// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package hcproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HealthCheckClient is the client API for HealthCheck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckClient interface {
	Subscribe(ctx context.Context, in *SubPayload, opts ...grpc.CallOption) (HealthCheck_SubscribeClient, error)
	Unsubscribe(ctx context.Context, in *SubPayload, opts ...grpc.CallOption) (*Ack, error)
}

type healthCheckClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckClient(cc grpc.ClientConnInterface) HealthCheckClient {
	return &healthCheckClient{cc}
}

func (c *healthCheckClient) Subscribe(ctx context.Context, in *SubPayload, opts ...grpc.CallOption) (HealthCheck_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &HealthCheck_ServiceDesc.Streams[0], "/healthcheck.HealthCheck/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &healthCheckSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HealthCheck_SubscribeClient interface {
	Recv() (*HealthCheckMap, error)
	grpc.ClientStream
}

type healthCheckSubscribeClient struct {
	grpc.ClientStream
}

func (x *healthCheckSubscribeClient) Recv() (*HealthCheckMap, error) {
	m := new(HealthCheckMap)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *healthCheckClient) Unsubscribe(ctx context.Context, in *SubPayload, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/healthcheck.HealthCheck/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckServer is the server API for HealthCheck service.
// All implementations must embed UnimplementedHealthCheckServer
// for forward compatibility
type HealthCheckServer interface {
	Subscribe(*SubPayload, HealthCheck_SubscribeServer) error
	Unsubscribe(context.Context, *SubPayload) (*Ack, error)
	mustEmbedUnimplementedHealthCheckServer()
}

// UnimplementedHealthCheckServer must be embedded to have forward compatible implementations.
type UnimplementedHealthCheckServer struct {
}

func (UnimplementedHealthCheckServer) Subscribe(*SubPayload, HealthCheck_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedHealthCheckServer) Unsubscribe(context.Context, *SubPayload) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedHealthCheckServer) mustEmbedUnimplementedHealthCheckServer() {}

// UnsafeHealthCheckServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckServer will
// result in compilation errors.
type UnsafeHealthCheckServer interface {
	mustEmbedUnimplementedHealthCheckServer()
}

func RegisterHealthCheckServer(s grpc.ServiceRegistrar, srv HealthCheckServer) {
	s.RegisterService(&HealthCheck_ServiceDesc, srv)
}

func _HealthCheck_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubPayload)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HealthCheckServer).Subscribe(m, &healthCheckSubscribeServer{stream})
}

type HealthCheck_SubscribeServer interface {
	Send(*HealthCheckMap) error
	grpc.ServerStream
}

type healthCheckSubscribeServer struct {
	grpc.ServerStream
}

func (x *healthCheckSubscribeServer) Send(m *HealthCheckMap) error {
	return x.ServerStream.SendMsg(m)
}

func _HealthCheck_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheck.HealthCheck/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServer).Unsubscribe(ctx, req.(*SubPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthCheck_ServiceDesc is the grpc.ServiceDesc for HealthCheck service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthCheck_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "healthcheck.HealthCheck",
	HandlerType: (*HealthCheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unsubscribe",
			Handler:    _HealthCheck_Unsubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _HealthCheck_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "healthcheck.proto",
}
